[env:esp32-s2-tester]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, default
build_type = release
upload_speed = 921600
board_build.sdkconfig_defaults = sdkconfig.defaults
board_build.sdkconfig_options =
  CONFIG_ARDUINO_LOOP_STACK_SIZE=16384
lib_deps =
  adafruit/Adafruit NeoPixel
  bblanchon/ArduinoJson
build_flags =
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DENABLE_SERIAL_OUTPUT=1
  -DENABLE_DEBUG_SERIAL_CHECKPOINTS=0
